apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - cluster-secret-store.yaml
  - external-secret-database.yaml
  - external-secret-llm.yaml
  - external-secret-scm.yaml
  - external-secret-webhook.yaml
  - external-secret-jira.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: ai-code-reviewer
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
