apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-reviewer

resources:
  - namespace.yaml
  - configmaps/app-config.yaml
  - redis/statefulset.yaml
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - api-gateway/hpa.yaml
  - llm-worker/deployment.yaml
  - llm-worker/hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: ai-code-reviewer
  app.kubernetes.io/managed-by: kustomize
