apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ai-reviewer
  labels:
    app.kubernetes.io/name: app-config
    app.kubernetes.io/part-of: ai-code-reviewer
data:
  redis.host: "redis"
  redis.port: "6379"
  llm.provider: "openai"
  llm.base-url: "https://api.openai.com/v1"
  llm.model: "gpt-4o"
  gitlab.enabled: "true"
  github.enabled: "false"
